# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe1322dc8aea59969de1f22434d9714b5c63ca2cd949c7934d82c7e71877aef522c694c9d44076f0f9a3e71f6f5b9705653326996fb438b065f1f309487e0090

test:
  secret_key_base: 233b212a708ab60acacdd701a3bc2cda30b3188f474fb5140c2379d3a78a5c4c276e4f6f2ce479bda2b676ebda3ca3d3bfc1fb1f706741e80fbc94ff61e70fc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
